// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaPichichus.Context;

#nullable disable

namespace VeterinariaPichichus.Migrations
{
    [DbContext(typeof(DuenioContext))]
    [Migration("20241112224112_sql_test")]
    partial class sql_test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaPichichus.Models.Duenio", b =>
                {
                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("DNI");

                    b.HasIndex("MascotaId")
                        .IsUnique();

                    b.ToTable("Duenios");
                });

            modelBuilder.Entity("VeterinariaPichichus.Models.Mascota", b =>
                {
                    b.Property<int>("idMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMascota"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("idMascota");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("VeterinariaPichichus.Models.Duenio", b =>
                {
                    b.HasOne("VeterinariaPichichus.Models.Mascota", "MascotaDuenio")
                        .WithOne("Duenio")
                        .HasForeignKey("VeterinariaPichichus.Models.Duenio", "MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MascotaDuenio");
                });

            modelBuilder.Entity("VeterinariaPichichus.Models.Mascota", b =>
                {
                    b.Navigation("Duenio");
                });
#pragma warning restore 612, 618
        }
    }
}
